### ISSUE TITLE
VIM 7.0 Doesn't Work with NERDTree Any More

### ISSUE THREAD

**Issue by flowjzh** [scrooloose/nerdtree#182]
After upgrade to the latest version of NERDTree, it doesn't work with vim 7.0.237 (which is shipped with RHEL / CentOS 5) any more. Error log show as:

Error detected while processing function <SNR>15_toggle..<SNR>15_initNerdTree..1
02..100:
line    7:
E118: Too many arguments for function: globpath
E15: Invalid expression: globpath(globDir, '_',1) . "\n" . globpath(globDir, '._
',1)

**Comment by comm1x** [comment]
@diffsky Thanks

**Comment by PhilRunninger** [comment]
Is it not possible to upgrade vim on CentOS?

**Comment by diffsky** [comment]
On CentOS 7.4, this works for me, to upgrade vim:
```
curl -L https://copr.fedorainfracloud.org/coprs/mcepl/vim8/repo/epel-7/mcepl-vim8-epel-7.repo -o /etc/yum.repos.d/mcepl-vim8-epel-7.repo && yum update vim* -y
```

**Comment by PhilRunninger** [comment]
Can we consider this closed then?
